# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180603_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='mood',
        ),
    ]
