# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 20:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('servings', models.IntegerField(default=1)),
                ('preparation_time', models.IntegerField(default=1)),
                ('cooking_time', models.IntegerField(default=1)),
                ('image1', models.ImageField(upload_to=b'static/image')),
                ('image2', models.ImageField(upload_to=b'static/image')),
                ('image3', models.ImageField(upload_to=b'static/image')),
                ('image4', models.ImageField(upload_to=b'static/image')),
                ('price_level', models.CharField(choices=[(b'$', b'$'), (b'$$', b'$$'), (b'$$$', b'$$$')], default=b'text', max_length=10)),
                ('mood', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[(b'Snack', b'Snack'), (b'Break fast', b'Break fast'), (b'Dinner/Lunch', b'Dinner/Lunch'), (b'Drink', b'Drink'), (b'Dessert', b'Dessert')], default=b'text', max_length=30)),
                ('Calories', models.FloatField(default=0)),
                ('Fat', models.FloatField(default=0)),
                ('Carbohydrates', models.FloatField(default=0)),
                ('Protein', models.FloatField(default=0)),
                ('Cholesterol', models.FloatField(default=0)),
                ('Sodium', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Meal'),
        ),
        migrations.AddField(
            model_name='direction',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Meal'),
        ),
    ]
