# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_meal_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='mood',
            field=models.CharField(choices=[(b'Happy', b'Happy'), (b'Bored', b'Bored'), (b'Sad', b'Sad'), (b'Angry', b'Angry')], default=b'Happy', max_length=30),
        ),
    ]
